[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
description = ""
name = "test-project"
requires-python = ">=3.12.0"
version = "1.0.0"
dependencies = [
    "check-wheel-contents==0.6.1"
]
